[project]
name = "homelab-hdmi-switch"
version = "0.1.0"
description = "Simple Controller for TESMart HDMI Switch"
readme = "README.md"
authors = [
    { name = "Matthew J. Morrison", email = "mattjmorrison@mattjmorrison.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pyserial>=3.5",
    "gunicorn>=23.0.0",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-ruff>=0.5",
    "pytest-ty>=0.2.1",
    "ruff>=0.16.2",
    "ty>=0.0.70",
]

[tool.pytest.ini_options]
addopts = "--ruff --ruff-format --ty --cov=homelab_hdmi_switch"

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.ruff.lint]
extend-select = ["ANN"]
